# Site settings
# in the templates available like {{ site.myvariable }}.
title: India Cricketer
email: contact@vk.com
brand: Virat Kohli
headline: Indian Cricketer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: contact@vk.com
phone: +91-8800880088



